/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manager;

/**
 *
 * @author dasep
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rekamMedis = new javax.swing.JButton();
        rekamMedis2 = new javax.swing.JButton();
        rekamMedis3 = new javax.swing.JButton();
        rekamMedis4 = new javax.swing.JButton();
        rekamMedis5 = new javax.swing.JButton();
        rekamMedis1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(225, 225, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KLINIK BU ITA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pusat Pelayanan Masyarakat");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kota Jakarta Utara");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jPanel1.setBackground(new java.awt.Color(71, 82, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selamat Datang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 126, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dasep Depiyawan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        logout.setBackground(new java.awt.Color(48, 37, 40));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 50));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 320));

        jPanel4.setBackground(new java.awt.Color(71, 82, 83));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rekamMedis.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis.setText("PENDAFTARAN PASIEN");
        rekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedisActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 50));

        rekamMedis2.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis2.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis2.setText("TINDAK LANJUT");
        rekamMedis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis2ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 50));

        rekamMedis3.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis3.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis3.setText("REKAM MEDIS");
        rekamMedis3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis3ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 180, 50));

        rekamMedis4.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis4.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis4.setText("TRANSAKSI OBAT");
        rekamMedis4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis4ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 180, 50));

        rekamMedis5.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis5.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis5.setText("BIAYA PASIEN ");
        rekamMedis5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis5ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 180, 50));

        rekamMedis1.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis1.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis1.setText("Tambah Akun");
        rekamMedis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis1ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 550, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedisActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rekamMedisActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void rekamMedis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekamMedis1ActionPerformed

    private void rekamMedis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekamMedis2ActionPerformed

    private void rekamMedis3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekamMedis3ActionPerformed

    private void rekamMedis4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekamMedis4ActionPerformed

    private void rekamMedis5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekamMedis5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton rekamMedis;
    private javax.swing.JButton rekamMedis1;
    private javax.swing.JButton rekamMedis2;
    private javax.swing.JButton rekamMedis3;
    private javax.swing.JButton rekamMedis4;
    private javax.swing.JButton rekamMedis5;
    // End of variables declaration//GEN-END:variables
}
