/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manager;
import Main.Login;
/**
 *
 * @author dasep
 */
public class HomeManager extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public HomeManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        daftarpasien = new javax.swing.JButton();
        tindaklanjut = new javax.swing.JButton();
        rekamMedis3 = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        biaya = new javax.swing.JButton();
        rekamMedis1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(225, 225, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KLINIK BIDAN ITA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pusat Pelayanan Masyarakat");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        jPanel1.setBackground(new java.awt.Color(71, 82, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selamat Datang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 126, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dasep Depiyawan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        logout.setBackground(new java.awt.Color(48, 37, 40));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 50));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 320));

        jPanel4.setBackground(new java.awt.Color(71, 82, 83));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarpasien.setBackground(new java.awt.Color(48, 37, 40));
        daftarpasien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        daftarpasien.setForeground(new java.awt.Color(255, 255, 255));
        daftarpasien.setText("PENDAFTARAN PASIEN");
        daftarpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarpasienActionPerformed(evt);
            }
        });
        jPanel4.add(daftarpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 50));

        tindaklanjut.setBackground(new java.awt.Color(48, 37, 40));
        tindaklanjut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tindaklanjut.setForeground(new java.awt.Color(255, 255, 255));
        tindaklanjut.setText("TINDAK LANJUT");
        tindaklanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindaklanjutActionPerformed(evt);
            }
        });
        jPanel4.add(tindaklanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 50));

        rekamMedis3.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis3.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis3.setText("REKAM MEDIS");
        rekamMedis3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis3ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 180, 50));

        transaksi.setBackground(new java.awt.Color(48, 37, 40));
        transaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        transaksi.setForeground(new java.awt.Color(255, 255, 255));
        transaksi.setText("TRANSAKSI OBAT");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jPanel4.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 180, 50));

        biaya.setBackground(new java.awt.Color(48, 37, 40));
        biaya.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        biaya.setForeground(new java.awt.Color(255, 255, 255));
        biaya.setText("BIAYA PASIEN ");
        biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaActionPerformed(evt);
            }
        });
        jPanel4.add(biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 180, 50));

        rekamMedis1.setBackground(new java.awt.Color(48, 37, 40));
        rekamMedis1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rekamMedis1.setForeground(new java.awt.Color(255, 255, 255));
        rekamMedis1.setText("TAMBAH AKUN");
        rekamMedis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekamMedis1ActionPerformed(evt);
            }
        });
        jPanel4.add(rekamMedis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 550, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarpasienActionPerformed
        // TODO add your handling code here:
       Pendaftaran_Pasien a = new Pendaftaran_Pasien();
       a.setVisible(true);
    }//GEN-LAST:event_daftarpasienActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login a = new Login();
        a.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void rekamMedis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis1ActionPerformed
        // TODO add your handling code here:
        Transaksi_obat a  = new Transaksi_obat();
        a.setVisible(true);
    }//GEN-LAST:event_rekamMedis1ActionPerformed

    private void tindaklanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindaklanjutActionPerformed
        // TODO add your handling code here:
        Tindak_Lanjut a  = new Tindak_Lanjut();
        a.setVisible(true);
    }//GEN-LAST:event_tindaklanjutActionPerformed

    private void rekamMedis3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekamMedis3ActionPerformed
        // TODO add your handling code here:
        Rekam_Medis a  = new Rekam_Medis();
        a.setVisible(true);
    }//GEN-LAST:event_rekamMedis3ActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        Transaksi_obat a  = new Transaksi_obat();
        a.setVisible(true);
    }//GEN-LAST:event_transaksiActionPerformed

    private void biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaActionPerformed
        // TODO add your handling code here:
        Biaya_pasien a  = new Biaya_pasien();
        a.setVisible(true);
    }//GEN-LAST:event_biayaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biaya;
    private javax.swing.JButton daftarpasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton rekamMedis1;
    private javax.swing.JButton rekamMedis3;
    private javax.swing.JButton tindaklanjut;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
