/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.operator;
import Conection.Conn ;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
//import com.raven.datechooser.SelectedDate;
//import com.toedter.calendar.JCalendar;
import java.awt.Color;
/**
 *
 * @author cad-server
 */
public class Daftar_Pasien extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_Pasien
     */
    public Daftar_Pasien() {
        initComponents();
        idPasien();
        id_pasien.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectedDate1 = new org.netbeans.modules.form.InvalidComponent();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_pasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tempat_lahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        no_telpon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        no_bpjs = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PENDAFTARAN PASIEN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 20));

        jPanel3.setBackground(new java.awt.Color(71, 82, 83));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Data Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(java.awt.Color.white);
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alamat");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(340, 130, 80, 33);

        id_pasien.setBackground(new java.awt.Color(149, 72, 91));
        id_pasien.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(id_pasien);
        id_pasien.setBounds(120, 30, 180, 33);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pasien");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 80, 100, 33);

        nama_pasien.setBackground(new java.awt.Color(149, 72, 91));
        nama_pasien.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(nama_pasien);
        nama_pasien.setBounds(120, 80, 180, 33);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Tanggal Lahir");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 180, 100, 33);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Tempat Lahir");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 130, 100, 33);

        tempat_lahir.setBackground(new java.awt.Color(149, 72, 91));
        tempat_lahir.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(tempat_lahir);
        tempat_lahir.setBounds(120, 130, 180, 33);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Pasien");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(29, 30, 80, 33);

        jenis_kelamin.setBackground(new java.awt.Color(149, 72, 91));
        jenis_kelamin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jenis_kelamin.setForeground(new java.awt.Color(255, 255, 255));
        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel3.add(jenis_kelamin);
        jenis_kelamin.setBounds(420, 30, 230, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Kelamin");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(330, 30, 80, 33);

        alamat.setBackground(new java.awt.Color(149, 72, 91));
        alamat.setColumns(20);
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(420, 140, 230, 96);

        no_telpon.setBackground(new java.awt.Color(149, 72, 91));
        no_telpon.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(no_telpon);
        no_telpon.setBounds(120, 230, 180, 33);

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("No Telpon");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 230, 100, 33);

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("No BPJS");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(340, 80, 100, 33);

        no_bpjs.setBackground(new java.awt.Color(149, 72, 91));
        no_bpjs.setForeground(new java.awt.Color(255, 255, 255));
        no_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_bpjsActionPerformed(evt);
            }
        });
        jPanel3.add(no_bpjs);
        no_bpjs.setBounds(420, 80, 230, 33);

        tambah.setBackground(new java.awt.Color(48, 37, 40));
        tambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel3.add(tambah);
        tambah.setBounds(540, 240, 107, 38);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 330));

        jPanel2.setBackground(new java.awt.Color(181, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void idPasien(){
        try {
            String sql  = "SELECT * FROM tbl_pasien order by id_pasien desc ";
            java.sql.Connection conn = (Connection)Conn.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                String nofak = rs.getString("id_pasien").substring(3);
                String AN    = "" + (Integer.parseInt(nofak) + 1 );
                String nol   = "" ;
                
                if(AN.length() == 1){
                    nol = "000" ;
                }else if(AN.length() == 2){
                    nol = "00" ;
                }else if(AN.length() == 3){
                    nol = "0" ;
                }else if(AN.length() == 4){
                    nol = "" ;
                }
                id_pasien.setText("PSN" + nol + AN);
            }else {
                id_pasien.setText("PSN0001");
            }
        
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private  String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        Daftar_Pasien a = new Daftar_Pasien();
        String tgl_daftar =  a.getTanggal();
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal_lahir = "d" ; //format1.format(tgl_lahir.getDate());
        if(id_pasien.getText().equals("") || nama_pasien.getText().equals("")||  tempat_lahir.getText().equals("") || alamat.getText().equals("")
                || no_telpon.getText().equals("") || no_bpjs.getText().equals("")){
            JOptionPane.showMessageDialog(null,"field kosong");
        }else {
            try {
                String sql = "INSERT INTO  tbl_pasien ("
                + " id_pasien , nama , tgl_daftar ,  tempat_lahir ,tgl_lahir , jenis_kelamin ,"
                        + "alamat , no_telp , no_bpjs , status ,transaksi) values "
                + "('"+ id_pasien.getText() +"' , '"+ nama_pasien.getText() +"' , '"  + tgl_daftar +  "' ,"
                        + " '"+ tempat_lahir.getText()  +"' , '"+ tanggal_lahir  +"' , '"+ jenis_kelamin.getSelectedItem()  +"' ,"
                        + " '"+ alamat.getText()  +"' , '"+ no_telpon.getText()  +"' , '"+ no_bpjs.getText()  +"' , 'BELUM DI PERIKSA' ,'NOK') " ;
                
               String sql2 = "insert into rekam_medis(id_pasien , nama_pasien , jenis_kelamin , tempat_lahir ,"
                       + " alamat , no_telp , no_bpjs , tgl_lahir )values ('"+ id_pasien.getText() +"' , '"+ nama_pasien.getText() +"' , '"+ jenis_kelamin.getSelectedItem() +"' ,  "
                       + " '"+ tempat_lahir.getText() +"' , '"+ alamat.getText() +"' , '"+ no_telpon.getText()  +"' , '"+ no_bpjs.getText() +"' , '"+ tanggal_lahir +"' ) ";
                
                java.sql.Connection conn = (Connection)Conn.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                java.sql.PreparedStatement pst2 = conn.prepareStatement(sql2);
                pst.execute();
                pst2.execute();
                JOptionPane.showMessageDialog(null,"Pasien Di Daftarkan");
                idPasien();
                reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    public void reset(){
        nama_pasien.setText("");
        //tgl_lahir.setText("");
        tempat_lahir.setText("") ;
        alamat.setText("");
        no_telpon.setText("");
        no_bpjs.setText("");
    }
    
    private void no_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_bpjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_bpjsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Pasien().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField no_bpjs;
    private javax.swing.JTextField no_telpon;
    private org.netbeans.modules.form.InvalidComponent selectedDate1;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tempat_lahir;
    // End of variables declaration//GEN-END:variables
}
