/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.operator;

import Conection.Conn;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author cad-server
 */
public class KartuPasien extends javax.swing.JFrame {

    /**
     * Creates new form KartuPasien
     */
    public KartuPasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        klik.setText("Cetak");
        klik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(klik, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(klik, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void klikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klikActionPerformed
        // TODO add your handling code here:
        try {
            File theDir = new File("C:/Backup File/");
                if (!theDir.exists()){
                    theDir.mkdirs();
                }
            String path  = "C://Backup File//Kartu Pasien.pdf" ;
            String  sql = "SELECT * from  tbl_pasien where id_pasien='PSN0001' " ;
            java.sql.Connection conn = (Connection)Conn.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            /* Step-2: Initialize PDF documents - logical objects */
        Rectangle pagesize = new Rectangle(350, 350);
        pagesize.setBackgroundColor(new BaseColor(0xFF, 0xFF, 0xDE));
        Document my_pdf_report = new Document(pagesize);
        Font F3 = FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.BLUE) ;
        PdfWriter.getInstance(my_pdf_report, new FileOutputStream(path));
        my_pdf_report.open();            
        my_pdf_report.add(new Paragraph("      "
                + "             KARTU BEROBAT PASIEN",F3));
        //we have four columns in our table
        my_pdf_report.add(new Paragraph("\n"));
        
        float[] columnWidths = {9 , 1  , 7};
        PdfPTable my_report_table = new PdfPTable(columnWidths);
       // Cell cell = new PDf;
        
        my_report_table.setWidthPercentage(100);
        //create a cell object
        PdfPCell table_cell;
        PdfPCell table_cell2;
        
        //  Font F = FontFactory.getFont(FontFactory.COURIER, 5 , Font.NORMAL, BaseColor.WHITE) ;
        Font F2 = FontFactory.getFont(FontFactory.COURIER, 12, Font.NORMAL, BaseColor.BLACK);
        res.next();                

            //my_report_table.setHeaderRows(1);       

        //kolom 1
        table_cell2 = new PdfPCell(new Phrase("Nama Pasien" , F2));
        // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
       
        table_cell2 = new PdfPCell(new Phrase(":" , F2));
       //  table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(res.getString("nama") , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        //kolom 2
        table_cell2 = new PdfPCell(new Phrase("ID Pasien" , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(":" , F2));
         //table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(res.getString("id_pasien") , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        
        //kolom 3
        table_cell2 = new PdfPCell(new Phrase("Tempat, Tanggal Lahir" , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(":" , F2));
         //table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(res.getString("tempat_lahir") + "," + res.getString("tgl_lahir")  , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        
        //kolom 3
        table_cell2 = new PdfPCell(new Phrase("Alamat" , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(":" , F2));
         //table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
        
        table_cell2 = new PdfPCell(new Phrase(res.getString("alamat") , F2));
       // table_cell2.setBorder(0);
        my_report_table.addCell(table_cell2);
       
             
        /* Attach report table to PDF */
        my_pdf_report.add(my_report_table);                       
        my_pdf_report.close();
             //JOptionPane.showMessageDialog(null,"Sukses");
             Desktop.getDesktop().open(new File(path));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_klikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartuPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartuPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartuPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartuPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KartuPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton klik;
    // End of variables declaration//GEN-END:variables
}
